const paymentMethodsReducer: object = {
  paymentMethods: [
    {
      id: 1,
      isSelected: true,
      methodImg: "method-1.png",
      cardNumber: "1234 - 5678 - 1234 - 4541",
      expiryDate: "11/21",
      firstName: "Jack",
      lastName: "A",
      cvv: "123",
    },
    {
      id: 2,
      isSelected: false,
      methodImg: "method-2.png",
      cardNumber: "1234 - 5678 - 1234 - 4242",
      expiryDate: "10/21",
      firstName: "A",
      lastName: "Nawaz",
      cvv: "456",
    },
    {
      id: 3,
      isSelected: false,
      methodImg: "method-3.png",
      cardNumber: "1234 - 5678 - 1234 - 1337",
      expiryDate: "9/21",
      firstName: "Bahzad",
      lastName: "A",
      cvv: "123",
    },
    {
      id: 4,
      isSelected: false,
      methodImg: "method-3.png",
      cardNumber: "1234 - 5678 - 1234 - 2455",
      expiryDate: "12/21",
      firstName: "Ammad",
      lastName: "A",
      cvv: "456",
    },
  ],
  selectedMethod: {
    id: 1,
    isSelected: true,
    methodImg: "method-1.png",
    cardNumber: "1234 - 5678 - 1234 - 4541",
    expiryDate: "11/21",
    firstName: "Jack",
    lastName: "A",
    cvv: "123",
  },
  toggleAddCardPopup: false,
  toggleEditCardPopup: false,
  checkSaveInfo: false,
};

export default paymentMethodsReducer;
